
import { initializeApp } from "firebase/app";


const firebaseConfig = {
  apiKey: "AIzaSyCqdbFdcPnki7xwqehdkBNzaBAZJyyS8JA",
  authDomain: "login-auth-b90f5.firebaseapp.com",
  projectId: "login-auth-b90f5",
  storageBucket: "login-auth-b90f5.appspot.com",
  messagingSenderId: "133902467253",
  appId: "1:133902467253:web:d86d301c207afbb049fefc",
  measurementId: "G-98QRVRDZLL"
};


export const app = initializeApp(firebaseConfig);
